version: 2.1
orbs:
  firebase-deploy: noyo/firebase-deploy@0.1.1
jobs:
  build:
    docker:
      - image: circleci/node@3.0.0
    steps:
      - checkout
      - run: npm run build
      - run: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
  test:
    docker:
      - image: circleci/node@3.0.0
    steps:
      - checkout
      - run: npm run test
workflows:
  version: 2.1
  test_and_build:
    jobs:
      - test
      - build
